// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.1
//   protoc               v3.19.6
// source: proto/todo.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "todo";

export interface Empty {
}

export interface Todo {
  id: number;
  task: string;
}

export interface GetTodoId {
  id: number;
}

export interface Todos {
  todos: Todo[];
}

export const TODO_PACKAGE_NAME = "todo";

export interface TodoServiceClient {
  getAllTodos(request: Empty): Observable<Todos>;

  postTodo(request: Todo): Observable<Todo>;

  getTodo(request: GetTodoId): Observable<Todo>;

  deleteTodo(request: GetTodoId): Observable<Empty>;
}

export interface TodoServiceController {
  getAllTodos(request: Empty): Promise<Todos> | Observable<Todos> | Todos;

  postTodo(request: Todo): Promise<Todo> | Observable<Todo> | Todo;

  getTodo(request: GetTodoId): Promise<Todo> | Observable<Todo> | Todo;

  deleteTodo(request: GetTodoId): Promise<Empty> | Observable<Empty> | Empty;
}

export function TodoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getAllTodos", "postTodo", "getTodo", "deleteTodo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TODO_SERVICE_NAME = "TodoService";
